import {
  Department,
  SchoolClass,
  Student,
  User,
  OfficialNotice,
  AttendanceRecord,
  SchoolConfig,
  WorkshopViolationRecord,
  CompetencyUnit,
  StudentCompetencyAssessment,
  Holiday,
  SchoolTenant,
  DirectorateCircular,
  SchoolInspectionReport,
} from '@/types';

export const DEFAULT_EGYPTIAN_HOLIDAYS: Holiday[] = [
  {
    id: 'hol_6oct',
    name: 'عيد القوات المسلحة (نصر 6 أكتوبر)',
    startDate: '2025-10-06',
    endDate: '2025-10-06',
    type: 'official',
    description: 'عطلة رسمية بمناسبة ذكرى نصر أكتوبر المجيد',
  },
  {
    id: 'hol_coptic_xmas',
    name: 'عيد الميلاد المجيد',
    startDate: '2026-01-07',
    endDate: '2026-01-07',
    type: 'official',
    description: 'عطلة رسمية بمناسبة عيد الميلاد المجيد',
  },
  {
    id: 'hol_25jan',
    name: 'ثورة 25 يناير وعيد الشرطة',
    startDate: '2026-01-25',
    endDate: '2026-01-25',
    type: 'official',
    description: 'عطلة رسمية بمناسبة ثورة 25 يناير وعيد الشرطة',
  },
  {
    id: 'hol_midyear',
    name: 'إجازة نصف العام الدراسي',
    startDate: '2026-01-24',
    endDate: '2026-02-05',
    type: 'official',
    isTermBreak: true,
    description: 'إجازة منتصف العام المعتمدة من وزارة التربية والتعليم',
  },
  {
    id: 'hol_eid_fitr',
    name: 'عيد الفطر المبارك',
    startDate: '2026-03-20',
    endDate: '2026-03-23',
    type: 'official',
    description: 'عطلة رسمية بمناسبة عيد الفطر المبارك',
  },
  {
    id: 'hol_sham_nessim',
    name: 'عيد شم النسيم',
    startDate: '2026-04-13',
    endDate: '2026-04-13',
    type: 'official',
    description: 'عطلة رسمية بمناسبة عيد الربيع وشم النسيم',
  },
  {
    id: 'hol_sinai',
    name: 'عيد تحرير سيناء',
    startDate: '2026-04-25',
    endDate: '2026-04-25',
    type: 'official',
    description: 'عطلة رسمية بمناسبة ذكرى تحرير سيناء',
  },
  {
    id: 'hol_labor',
    name: 'عيد العمال',
    startDate: '2026-05-01',
    endDate: '2026-05-01',
    type: 'official',
    description: 'عطلة رسمية بمناسبة عيد العمال العالمي',
  },
  {
    id: 'hol_eid_adha',
    name: 'عيد الأضحى المبارك',
    startDate: '2026-05-26',
    endDate: '2026-05-30',
    type: 'official',
    description: 'عطلة رسمية بمناسبة وقفة عرفات وعيد الأضحى المبارك',
  },
];

export const DEFAULT_SCHOOLS: SchoolTenant[] = [
  {
    id: 'sch_cairo_abbassia',
    name: 'مدرسة العباسية الثانوية الصناعية الميكانيكية العسكرية بنين',
    code: '10201',
    accessPin: '10201',
    schoolUsername: '10201',
    directorate: 'مديرية التربية والتعليم بالقاهرة',
    administration: 'إدارة الوايلي التعليمية',
    systemType: '3_years',
    shiftType: 'single_morning',
    workDaysScheme: 'sun_to_thu',
    address: 'شارع العباسية، الوايلي، القاهرة',
    phone: '0224821000',
    principalName: 'أ.د. محمود إبراهيم النجار',
    isActive: true,
    createdAt: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'sch_giza_imaba',
    name: 'مدرسة إمبابة الثانوية الصناعية بنين',
    code: '10405',
    accessPin: '10405',
    schoolUsername: '10405',
    directorate: 'مديرية التربية والتعليم بالجيزة',
    administration: 'إدارة شمال الجيزة التعليمية',
    systemType: '3_years',
    shiftType: 'single_morning',
    workDaysScheme: 'sun_to_thu',
    address: 'شارع السودان، إمبابة، الجيزة',
    phone: '0233145000',
    principalName: 'م. عصام عبد الرحمن',
    isActive: true,
    createdAt: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'sch_alex_tousson',
    name: 'مدرسة طوسون الثانوية الصناعية المتقدمة (5 سنوات)',
    code: '20108',
    accessPin: '20108',
    schoolUsername: '20108',
    directorate: 'مديرية التربية والتعليم بالإسكندرية',
    administration: 'إدارة المنتزه التعليمية',
    systemType: '5_years_advanced',
    shiftType: 'single_morning',
    workDaysScheme: 'sat_to_thu',
    address: 'طوسون، أبو قير، الإسكندرية',
    phone: '035612300',
    principalName: 'د. أشرف فوزي جرجس',
    isActive: true,
    createdAt: '2025-09-01T00:00:00.000Z',
  },
];

export const DEFAULT_DIRECTORATE_CIRCULARS: DirectorateCircular[] = [
  {
    id: 'circ_2026_01',
    circularNumber: 'ك/د-2026/01',
    title: 'تأكيد الالتزام الصارم بحد الـ 85% لحضور الورش لدخول التقييم النهائي',
    subject: 'cbe',
    content: 'بناءً على القرار الوزاري المنظم لتقييم الجدارات المهنية لطلاب التعليم الفني، يُحظر حظراً تاماً دخول أي طالب لا يستوفي نسبة 85% من إجمالي الساعات المقررة للورش والتدريب العملي للتقييم النهائي لوحدات الجدارات.',
    issuedDate: '2025-10-15',
    priority: 'urgent',
    targetScope: 'all',
    acknowledgedBySchoolIds: ['sch_cairo_abbassia', 'sch_giza_imaba'],
    issuedBy: 'د. حسام الدين عبد القادر - مدير عام التعليم الفني بالمديرية',
  },
  {
    id: 'circ_2026_02',
    circularNumber: 'ك/د-2026/02',
    title: 'خطة تشديد إجراءات السلامة والصحة المهنية (HSE) ومهمات الوقاية',
    subject: 'safety',
    content: 'التأكيد على مديري المدارس الفنية ورؤساء الأقسام الصناعية بعدم السماح لأي طالب بالتواجد داخل الورش الميكانيكية والكهربائية بدون ارتداء مهمات الوقاية الشخصية (الأفرول وحذاء الأمان والنظارات الواقية) وتفتيش لوحات قواطع الطوارئ أسبوعياً.',
    issuedDate: '2025-11-02',
    priority: 'high',
    targetScope: 'all',
    acknowledgedBySchoolIds: ['sch_cairo_abbassia'],
    issuedBy: 'د. حسام الدين عبد القادر - مدير عام التعليم الفني بالمديرية',
  },
  {
    id: 'circ_2026_03',
    circularNumber: 'ك/د-2026/03',
    title: 'مواعيد انعقاد لجان التحقق الخارجي المعتمدة وممثلي سوق العمل',
    subject: 'cbe',
    content: 'تحديد المواعيد الزمنية لسحب عينات التحقق الخارجي لتقييمات الفصل الدراسي الأول بالتنسيق مع الغرف الصناعية وممثلي القطاع الخاص المعتمدين.',
    issuedDate: '2025-12-10',
    priority: 'normal',
    targetScope: 'all',
    acknowledgedBySchoolIds: ['sch_cairo_abbassia', 'sch_alex_tousson'],
    issuedBy: 'د. حسام الدين عبد القادر - مدير عام التعليم الفني بالمديرية',
  },
];

export const DEFAULT_INSPECTION_REPORTS: SchoolInspectionReport[] = [
  {
    id: 'insp_2026_01',
    reportNumber: 'تفتيش-2026/01',
    schoolId: 'sch_cairo_abbassia',
    schoolName: 'مدرسة العباسية الثانوية الصناعية الميكانيكية العسكرية بنين',
    inspectorName: 'م. أحمد كمال الدين (موجه عام مركزي بالمديرية)',
    visitDate: '2025-11-18',
    departmentInspected: 'قسم تشغيل المعادن والخراطة الميكانيكية',
    disciplineRating: 'excellent',
    ppeComplianceRating: 'compliant',
    competencyAuditStatus: 'verified',
    workshopAttendanceRate: 92,
    notes: 'انتظام متميز للطلاب والمدربين، دفاتر الحضور وسجلات التقييم محدثة ومطابقة لمصفوفة الجدارات، مهمات الوقاية متوفرة وملتزم بها.',
    recommendations: 'صرف مكافأة تميز لفريق ورشة الخراطة، والاستمرار على نفس المستوى في التوثيق.',
    status: 'resolved',
  },
  {
    id: 'insp_2026_02',
    reportNumber: 'تفتيش-2026/02',
    schoolId: 'sch_giza_imaba',
    schoolName: 'مدرسة إمبابة الثانوية الصناعية بنين',
    inspectorName: 'أ. طارق عبد العليم (عضو التوجيه الفني)',
    visitDate: '2025-12-05',
    departmentInspected: 'قسم الكهرباء الصناعية والتحكم الآلي',
    disciplineRating: 'good',
    ppeComplianceRating: 'partial',
    competencyAuditStatus: 'pending_samples',
    workshopAttendanceRate: 83,
    notes: 'لوحظ نقص في نظارات الحماية الشخصية بورشة اللف والتركيبات، ونسبة الحضور لبعض فصول الصف الثاني أقل من 85%.',
    recommendations: 'توجيه إخطار عاجل لإدارة المدرسة لتدارك مهمات الوقاية واستدعاء أولياء أمور الطلاب المتجاوزين لنسبة الغياب.',
    status: 'pending_school_action',
  },
];

export const SCHOOL_CONFIG: SchoolConfig = {
  id: 'config_primary',
  schoolId: 'sch_cairo_abbassia',
  name: 'مدرسة العباسية الثانوية الصناعية الميكانيكية العسكرية بنين',
  directorate: 'مديرية التربية والتعليم بالقاهرة',
  administration: 'إدارة الوايلي التعليمية',
  academicYear: '2025 / 2026',
  currentTerm: 'الفصل الدراسي الأول',
  term1StartDate: '2025-09-20',
  term1EndDate: '2026-01-22',
  midYearBreakStartDate: '2026-01-24',
  midYearBreakEndDate: '2026-02-05',
  term2StartDate: '2026-02-07',
  term2EndDate: '2026-06-04',
  holidays: DEFAULT_EGYPTIAN_HOLIDAYS,
  schoolSystemType: 'both_systems', // يدعم نظامي الـ 3 سنوات والـ 5 سنوات
  schoolShiftType: 'single_morning', // فترة واحدة صباحية
  workDaysScheme: 'sun_to_thu',      // من الأحد إلى الخميس
  morningQueueTime: '07:30 ص',
  eveningQueueTime: '12:30 م',
  phone: '0224821000',
  address: 'شارع العباسية، القاهرة',
  postalCode: '11566',
  managerName: 'أ.د. محمود إبراهيم النجار',
  managerTitle: 'مدير عام المدرسة',
  studentAffairsHead: 'أ. سامح عبد الفتاح',
  studentAffairsAgent: 'أ. مجدي خليل',
  theoreticalMinAttendanceRate: 75,
  practicalMinAttendanceRate: 85,
};

export const MOCK_USERS: User[] = [
  {
    id: 'user_directorate',
    name: 'د. حسام الدين عبد القادر',
    username: 'directorate',
    password: '123',
    role: 'directorate_admin',
    roleTitle: 'مدير عام التعليم الفني بالمديرية (المشرف العام المركزي)',
    phone: '01000000000',
    schoolId: 'all',
    customPermissions: {
      canTakeAttendance: false,
      canManageStudents: true,
      canTransferStudents: true,
      canApproveExcuses: true,
      canIssueNotices: true,
      canManageSchoolSettings: true,
      canManageUsers: true,
      canViewReports: true,
      canManageCompetencies: true,
      canLogViolations: false,
      canManageSocialCases: true,
      canAuditAssessments: true,
      canManageDirectorate: true,
    },
  },
  {
    id: 'user_admin',
    name: 'أ.د. محمود إبراهيم النجار',
    username: 'admin',
    password: '123',
    role: 'principal',
    roleTitle: 'مدير عام المدرسة الصناعية / القائد التنفيذي',
    schoolId: 'sch_cairo_abbassia',
    phone: '0224821000',
    customPermissions: {
      canTakeAttendance: true,
      canManageStudents: true,
      canTransferStudents: true,
      canApproveExcuses: true,
      canIssueNotices: true,
      canManageSchoolSettings: true,
      canManageUsers: true,
      canViewReports: true,
      canManageCompetencies: true,
      canLogViolations: true,
      canManageSocialCases: true,
      canAuditAssessments: true,
      canManageDirectorate: false,
    },
  },
  {
    id: 'user_affairs_deputy',
    name: 'أ. سامح عبد الفتاح',
    username: 'affairs',
    password: '123',
    role: 'affairs_deputy',
    roleTitle: 'وكيل شئون الطلاب ولجنة الانضباط (المادة 25)',
    schoolId: 'sch_cairo_abbassia',
    phone: '01011122233',
    customPermissions: {
      canTakeAttendance: false,
      canManageStudents: true,
      canTransferStudents: true,
      canApproveExcuses: true,
      canIssueNotices: true,
      canManageSchoolSettings: false,
      canManageUsers: false,
      canViewReports: true,
      canManageCompetencies: false,
      canLogViolations: true,
      canManageSocialCases: false,
      canAuditAssessments: false,
      canManageDirectorate: false,
    },
  },
  {
    id: 'user_affairs_officer',
    name: 'أ. مجدي خليل منصور',
    username: 'officer',
    password: '123',
    role: 'affairs_officer',
    roleTitle: 'مسؤول سجلات الطلاب والإحصاء ودفتر 41 وسر 1',
    schoolId: 'sch_cairo_abbassia',
    phone: '01022233344',
    customPermissions: {
      canTakeAttendance: false,
      canManageStudents: true,
      canTransferStudents: false,
      canApproveExcuses: false,
      canIssueNotices: true,
      canManageSchoolSettings: false,
      canManageUsers: false,
      canViewReports: true,
      canManageCompetencies: false,
      canLogViolations: false,
      canManageSocialCases: false,
      canAuditAssessments: false,
      canManageDirectorate: false,
    },
  },
  {
    id: 'user_dept_head',
    name: 'م. عصام عبد الرحمن',
    username: 'dept_head',
    password: '123',
    role: 'dept_head',
    roleTitle: 'رئيس قسم التركيبات والمعدات الكهربية',
    schoolId: 'sch_cairo_abbassia',
    departmentId: 'dept_elec',
    phone: '01033344455',
    customPermissions: {
      canTakeAttendance: true,
      canManageStudents: false,
      canTransferStudents: false,
      canApproveExcuses: false,
      canIssueNotices: false,
      canManageSchoolSettings: false,
      canManageUsers: false,
      canViewReports: true,
      canManageCompetencies: true,
      canLogViolations: true,
      canManageSocialCases: false,
      canAuditAssessments: true,
      canManageDirectorate: false,
    },
  },
  {
    id: 'user_teacher',
    name: 'م. طارق حسن رضوان',
    username: 'teacher',
    password: '123',
    role: 'teacher',
    roleTitle: 'معلم ومدرب عملي - ورش الكهرباء',
    schoolId: 'sch_cairo_abbassia',
    departmentId: 'dept_elec',
    assignedClassIds: ['cls_elec_1_1', 'cls_elec_2_1'],
    phone: '01044455566',
    customPermissions: {
      canTakeAttendance: true,
      canManageStudents: false,
      canTransferStudents: false,
      canApproveExcuses: false,
      canIssueNotices: false,
      canManageSchoolSettings: false,
      canManageUsers: false,
      canViewReports: false,
      canManageCompetencies: true,
      canLogViolations: true,
      canManageSocialCases: false,
      canAuditAssessments: false,
      canManageDirectorate: false,
    },
  },
  {
    id: 'user_social_worker',
    name: 'أ. أحمد السيد إبراهيم',
    username: 'social',
    password: '123',
    role: 'social_worker',
    roleTitle: 'الأخصائي الاجتماعي والتربوي / منسق الحماية المدرسية',
    schoolId: 'sch_cairo_abbassia',
    phone: '01023456789',
    customPermissions: {
      canTakeAttendance: false,
      canManageStudents: false,
      canTransferStudents: false,
      canApproveExcuses: false,
      canIssueNotices: false,
      canManageSchoolSettings: false,
      canManageUsers: false,
      canViewReports: true,
      canManageCompetencies: false,
      canLogViolations: true,
      canManageSocialCases: true,
      canAuditAssessments: false,
      canManageDirectorate: false,
    },
  },
  {
    id: 'user_competency_verifier',
    name: 'د. هشام الشناوي',
    username: 'competency',
    password: '123',
    role: 'external_verifier',
    roleTitle: 'محقق جدارات ومقيم معتمد من الإدارة المركزية (CBE)',
    schoolId: 'sch_cairo_abbassia',
    phone: '01055566677',
    customPermissions: {
      canTakeAttendance: false,
      canManageStudents: false,
      canTransferStudents: false,
      canApproveExcuses: false,
      canIssueNotices: false,
      canManageSchoolSettings: false,
      canManageUsers: false,
      canViewReports: true,
      canManageCompetencies: true,
      canLogViolations: false,
      canManageSocialCases: false,
      canAuditAssessments: true,
      canManageDirectorate: false,
    },
  },
];

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: 'dept_elec',
    code: 'ELE',
    name: 'قسم التركيبات والمعدات الكهربية',
    description: 'تأهيل فنيين مهرة في صيانة وتمديد الشبكات واللوحات الكهربية والتحكم الآلي.',
    scientificSupervisorName: 'أ. حسام الدين عبد الله',
    practicalSupervisorName: 'م. عصام عبد الرحمن',
    headName: 'م. عصام عبد الرحمن',
    headPhone: '01001234567',
    iconName: 'Zap',
    totalStudents: 0,
    workshopCount: 3,
    availableGrades: [1, 2, 3],
  },
  {
    id: 'dept_mech',
    code: 'MEC',
    name: 'قسم تشغيل المعادن والميكانيكا',
    description: 'إكساب الطلاب جدارات الخراطة والتفريز والتشغيل اليدوي والآلي وبرمجة CNC.',
    scientificSupervisorName: 'أ. محمود فؤاد',
    practicalSupervisorName: 'م. طارق المنشاوي',
    headName: 'م. طارق محمود المنشاوي',
    headPhone: '01112345678',
    iconName: 'Cog',
    totalStudents: 0,
    workshopCount: 4,
    availableGrades: [1, 2, 3],
  },
  {
    id: 'dept_auto',
    code: 'AUT',
    name: 'قسم صيانة السيارات ومحركات الديزل',
    description: 'صيانة وإصلاح محركات البنزين والديزل ودوائر حقن الوقود والكهرباء والإلكترونيات للسيارات.',
    scientificSupervisorName: 'أ. نبيل إبراهيم',
    practicalSupervisorName: 'م. محمد أحمد عبد العال',
    headName: 'م. محمد أحمد عبد العال',
    headPhone: '01223456789',
    iconName: 'Car',
    totalStudents: 0,
    workshopCount: 2,
    availableGrades: [1, 2, 3],
  },
  {
    id: 'dept_ref',
    code: 'REF',
    name: 'قسم تكنولوجيا التبريد وتكييف الهواء',
    description: 'تركيب وصيانة وحدات التبريد التجاري والمنزلي وأجهزة التكييف المركزي والمستقل.',
    scientificSupervisorName: 'أ. سعيد عبد العظيم',
    practicalSupervisorName: 'م. حسام خليل',
    headName: 'م. حسام الدين خليل',
    headPhone: '01556789012',
    iconName: 'Snowflake',
    totalStudents: 0,
    workshopCount: 2,
    availableGrades: [1, 2, 3],
  },
];

export const MOCK_CLASSES: SchoolClass[] = [
  {
    id: 'cls_elec_1_1',
    name: '1 / 1 كهرباء (تركيبات ومعدات)',
    gradeLevel: 1,
    gradeName: 'الصف الأول الثانوي الصناعي',
    departmentId: 'dept_elec',
    departmentName: 'قسم التركيبات والمعدات الكهربية',
    supervisorTeacherId: 'user_teacher_1',
    supervisorTeacherName: 'أ. محمد السعيد',
    roomNumber: 'ورشة الكهرباء 1',
    studentCount: 0,
    shift: 'morning',
  },
  {
    id: 'cls_elec_2_1',
    name: '2 / 1 كهرباء (تركيبات ومعدات)',
    gradeLevel: 2,
    gradeName: 'الصف الثاني الثانوي الصناعي',
    departmentId: 'dept_elec',
    departmentName: 'قسم التركيبات والمعدات الكهربية',
    supervisorTeacherId: 'user_teacher_1',
    supervisorTeacherName: 'أ. محمد السعيد',
    roomNumber: 'ورشة الكهرباء 2',
    studentCount: 0,
    shift: 'morning',
  },
  {
    id: 'cls_mech_1_1',
    name: '1 / 1 ميكانيكا (تشغيل معادن)',
    gradeLevel: 1,
    gradeName: 'الصف الأول الثانوي الصناعي',
    departmentId: 'dept_mech',
    departmentName: 'قسم تشغيل المعادن والميكانيكا',
    supervisorTeacherId: 'user_teacher_2',
    supervisorTeacherName: 'أ. أحمد مصطفى',
    roomNumber: 'ورشة الخراطة والتشغيل',
    studentCount: 0,
    shift: 'morning',
  },
  {
    id: 'cls_auto_1_1',
    name: '1 / 1 سيارات (محركات وكهرباء)',
    gradeLevel: 1,
    gradeName: 'الصف الأول الثانوي الصناعي',
    departmentId: 'dept_auto',
    departmentName: 'قسم صيانة السيارات ومحركات الديزل',
    supervisorTeacherId: 'user_teacher_3',
    supervisorTeacherName: 'أ. سامح عبد الفتاح',
    roomNumber: 'عنبر صيانة المحركات',
    studentCount: 0,
    shift: 'morning',
  },
  {
    id: 'cls_ref_1_1',
    name: '1 / 1 تبريد وتكييف هواء',
    gradeLevel: 1,
    gradeName: 'الصف الأول الثانوي الصناعي',
    departmentId: 'dept_ref',
    departmentName: 'قسم تكنولوجيا التبريد وتكييف الهواء',
    supervisorTeacherId: 'user_teacher_4',
    supervisorTeacherName: 'أ. حسن القاضي',
    roomNumber: 'معمل التبريد والتكييف',
    studentCount: 0,
    shift: 'morning',
  },
];

export const MOCK_STUDENTS: Student[] = [];

export const MOCK_NOTICES: OfficialNotice[] = [];

export const MOCK_ATTENDANCE_HISTORY: AttendanceRecord[] = [];

export const MOCK_WORKSHOP_VIOLATIONS: WorkshopViolationRecord[] = [];

export const MOCK_COMPETENCY_UNITS: CompetencyUnit[] = [
  // ==========================================
  // قسم التركيبات والمعدات الكهربية (ELE)
  // ==========================================
  {
    id: 'unit_ele_101',
    code: 'ELE-101',
    name: 'تطبيق قواعد واشتراطات السلامة والصحة المهنية بالورش الكهربية',
    category: 'technical_core',
    departmentId: 'dept_elec',
    gradeLevel: 1,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 36,
    description: 'إكساب الطالب جدارات ارتداء مهمات الوقاية وتأمين بيئة العمل والتعامل مع مخاطر الصعق وطوارئ الحرائق الكهربية.',
    outcomes: [
      {
        id: 'lo_ele_101_1',
        code: 'LO 1',
        title: 'ارتداء واستخدام مهمات الوقاية الشخصية المناسبة للعمل الكهربي',
        description: 'ارتداء حذاء العزل والقفازات المعزولة ونظارة الحماية والبدلة القطنية.',
        weightHours: 12,
        requiredEvidences: ['performance_checklist'],
        performanceCriteria: ['يختار مهمات الوقاية طبقا لنوع المهمة', 'يرتدي القفازات العازلة باختبار سلامتها', 'يلتزم بارتداء حذاء الأمان العازل'],
      },
      {
        id: 'lo_ele_101_2',
        code: 'LO 2',
        title: 'تأمين لوحات التوزيع وقطع التيار قبل بدء العمل بالورشة',
        description: 'تطبيق إجراءات القفل والوسم (LOTO) واستخدام كاشف الجهد.',
        weightHours: 12,
        requiredEvidences: ['performance_checklist', 'knowledge_questioning'],
        performanceCriteria: ['يفصل القاطع الرئيسي للوحة', 'يضع لافتة التحذير وقفل الأمان', 'يختبر خلو الدائرة من الجهد بجهاز الفحص'],
      },
      {
        id: 'lo_ele_101_3',
        code: 'LO 3',
        title: 'التصرف السليم أثناء حالات الصعق وإطفاء حرائق الكهرباء',
        description: 'عزل المصاب واستخدام طفايات ثاني أكسيد الكربون والبودرة الجافة.',
        weightHours: 12,
        requiredEvidences: ['performance_checklist', 'knowledge_questioning'],
        performanceCriteria: ['يعزل مصدر التيار دون لمس المصاب باليد المجردة', 'يختار طفاية الحريق المناسبة (CO2)', 'يبلغ المشرف ويسجل تقرير الحادث'],
      },
    ],
  },
  {
    id: 'unit_ele_102',
    code: 'ELE-102',
    name: 'تنفيذ التمديدات الكهربية للأجهزة ودوائر الإنارة المنزلية',
    category: 'technical_core',
    departmentId: 'dept_elec',
    gradeLevel: 1,
    term: 'term_2',
    outcomesCount: 3,
    totalHours: 48,
    description: 'تنفيذ دوائر الإنارة البسيطة والديفياتوري والنجف وتوصيل البرايز ولوحات التوزيع الفرعية.',
    outcomes: [
      {
        id: 'lo_ele_102_1',
        code: 'LO 1',
        title: 'قراءة المخطط التنفيذي وتجهيز مسارات المواسير والأسلاك',
        description: 'تحديد أماكن البواطات والمفاتيح والبرايز طبقا للرسم الهندسي.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist'],
        performanceCriteria: ['يقرأ الرموز والمصطلحات الكهربية بدقة', 'يثبت البواطات والمواسير بالمناسيب المحددة', 'يسحب الأسلاك بالألوان المعتمدة للكود'],
      },
      {
        id: 'lo_ele_102_2',
        code: 'LO 2',
        title: 'توصيل واختبار دوائر الإنارة بالمفاتيح الفردية والمزدوجة والديفياتوري',
        description: 'ربط أطراف الأسلاك بالروزتات والمفاتيح واختبار استمرارية الدائرة.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['ينفذ التوصيل طبقا للمخطط', 'يربط الأسلاك بإحكام دون ترك نحاس مكشوف', 'يختبر عمل اللمبات والمفاتيح بنجاح'],
      },
      {
        id: 'lo_ele_102_3',
        code: 'LO 3',
        title: 'فحص واختبار عزل الدائرة وتوصيل خط التأريض الوقائي',
        description: 'قياس مقاومة العزل بجهاز الميجر واختبار فاعلية سلك الأرضي.',
        weightHours: 16,
        requiredEvidences: ['product_inspection', 'knowledge_questioning'],
        performanceCriteria: ['يقيس مقاومة العزل وتتجاوز 1 ميجا أوم', 'يوصل خط الأرضي لجميع البرايز', 'يسلم اللوحة في حالة تشغيل آمنة'],
      },
    ],
  },
  {
    id: 'unit_ele_201',
    code: 'ELE-201',
    name: 'لف وصيانة محولات الجهد المنخفض والمحركات الكهربية أحادية وثلاثية الأوجه',
    category: 'technical_core',
    departmentId: 'dept_elec',
    gradeLevel: 2,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 54,
    description: 'حساب وإسقاط ملفات المحركات، عزل المجاري، وتجربة المحرك تحت الحمل.',
    outcomes: [
      {
        id: 'lo_ele_201_1',
        code: 'LO 1',
        title: 'رفع بيانات المحرك القديم وحساب خطوة اللف وأقطار الأسلاك',
        description: 'تسجيل بيانات لوحة التسمية وحساب عدد اللفات والوزن.',
        weightHours: 18,
        requiredEvidences: ['performance_checklist', 'knowledge_questioning'],
        performanceCriteria: ['يرفع بيانات النيم بليت', 'يقيس قطر السلك بالميكرومتر بدقة', 'يعد جدول بيانات اللف'],
      },
      {
        id: 'lo_ele_201_2',
        code: 'LO 2',
        title: 'عزل المجاري وإسقاط الملفات والتربيط والورنكة',
        description: 'تنزيل السرايا وتثبيت الخوابير وعمل الكباري وتجفيف الورنيش.',
        weightHours: 18,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يعزل المجاري بورق البرشمان والميلار', 'يسقط السرايا دون خدش عزل السلك', 'يورنك العضو الساكن ويجففه بالفرن'],
      },
      {
        id: 'lo_ele_201_3',
        code: 'LO 3',
        title: 'إجراء الاختبارات الكهربية والميكانيكية للمحرك بعد التجميع',
        description: 'قياس سحب الأمبير بدون حمل وتيار البدء وسرعة الدوران RPM.',
        weightHours: 18,
        requiredEvidences: ['product_inspection'],
        performanceCriteria: ['يقيس تيار اللاحمل وتوازن الأوجه', 'يقيس سرعة الدوران بجهاز التاكوميتر', 'يتأكد من خلو المحرك من الاهتزاز والحرارة'],
      },
    ],
  },
  {
    id: 'unit_ele_301',
    code: 'ELE-301',
    name: 'تشغيل والتحكم في المحركات والآلات الكهربية بواسطة أجهزة الـ PLC',
    category: 'technical_core',
    departmentId: 'dept_elec',
    gradeLevel: 3,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 60,
    description: 'برمجة وتوصيل المتحكم المنطقي المبرمج PLC لتشغيل خطوط الإنتاج والمحركات الحثية.',
    outcomes: [
      {
        id: 'lo_ele_301_1',
        code: 'LO 1',
        title: 'رسم وتوصيل دوائر القوى والتحكم لجهاز الـ PLC والحساسات',
        description: 'ربط المداخل الرقمية والتناظرية والمخارج مع الكونتاكتورات.',
        weightHours: 20,
        requiredEvidences: ['performance_checklist'],
        performanceCriteria: ['يوصل مصدر التغذية DC/AC للـ PLC', 'يربط الحساسات والمفاتيح بنقاط الدخل', 'يربط الكونتاكتورات بنقاط الخرج مع الريليهات'],
      },
      {
        id: 'lo_ele_301_2',
        code: 'LO 2',
        title: 'كتابة واختبار برامج التحكم بلغة السلم Ladder Diagram',
        description: 'استخدام المؤقتات الزمنية Timers والعدادات Counters في التحكم.',
        weightHours: 20,
        requiredEvidences: ['product_inspection', 'knowledge_questioning'],
        performanceCriteria: ['يكتب كود السلم طبقا لتسلسل العمليات', 'يضبط المؤقتات الزمنية والماركرات', 'يحاكي البرنامج أونلاين قبل التحميل'],
      },
      {
        id: 'lo_ele_301_3',
        code: 'LO 3',
        title: 'تحميل البرنامج على جهاز الـ PLC وتشغيل المنظومة وكشف الأعطال',
        description: 'تنزيل البرنامج ومتابعة الإشارات الحية وتشخيص أخطاء التوصيل.',
        weightHours: 20,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يحمل البرنامج بكابل الاتصال بنجاح', 'يراقب تشغيل المحركات طبقا للسيناريو', 'يكتشف العطل ويعالجه من شاشة المراقبة'],
      },
    ],
  },

  // ==========================================
  // قسم صيانة وإصلاح السيارات (AUT)
  // ==========================================
  {
    id: 'unit_aut_101',
    code: 'AUT-101',
    name: 'فك وتجميع وضبط محركات الاحتراق الداخلي (بنزين / ديزل)',
    category: 'technical_core',
    departmentId: 'dept_auto',
    gradeLevel: 1,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 48,
    description: 'فك أجزاء المحرك الثابتة والمتحركة وفحص التآكل وتجميع المحرك وضبط التاكيهات وتوقيت الكاتينة.',
    outcomes: [
      {
        id: 'lo_aut_101_1',
        code: 'LO 1',
        title: 'فك أجزاء المحرك باستخدام العدد الخاصة وترتيبها على طاولة الفحص',
        description: 'فك وش السلندر، الكرتير، عمود الكرنك، البساتم، وعمود الكامات.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist'],
        performanceCriteria: ['يتبع تسلسل فك مسامير وش السلندر طبقا للكتالوج', 'يرتب البساتم وأغطية الكراسي بالأرقام', 'ينظف الأجزاء بسائل التنظيف المخصص'],
      },
      {
        id: 'lo_aut_101_2',
        code: 'LO 2',
        title: 'قياس خلوصات الشنابر والسبائك واستواء وش السلندر',
        description: 'استخدام الفيلر والميكرومتر وساعة القياس Dial Gauge.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يقيس خلوص فتحة الشنبر داخل الأسطوانة', 'يقيس خلوص سبيكة الكرنك والبييل بالبلاستيك جيج', 'يفحص استواء وش السلندر بالمسطرة الصلب والفيلر'],
      },
      {
        id: 'lo_aut_101_3',
        code: 'LO 3',
        title: 'تجميع المحرك وعزم المسامير بمفتاح العزم وضبط سير الكاتينة',
        description: 'ربط المسامير بالعزم المحدد وضبط علامات التوقيت وخلوص الصمامات.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يعزم مسامير الرأس بمفتاح العزم على مراحل', 'يطابق علامات توقيت عمود الكرنك والكامات', 'يضبط خلوص الصمامات (التاكيهات) طبقا للمواصفة'],
      },
    ],
  },
  {
    id: 'unit_aut_201',
    code: 'AUT-201',
    name: 'تشخيص وصيانة منظومات حقن الوقود الإلكتروني EFI وإدارة المحرك',
    category: 'technical_core',
    departmentId: 'dept_auto',
    gradeLevel: 2,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 50,
    description: 'فحص الحساسات والمشغلات، طلمبة ورشاشات الوقود، واستخدام أجهزة فحص الأعطال OBD-II.',
    outcomes: [
      {
        id: 'lo_aut_201_1',
        code: 'LO 1',
        title: 'فحص واختبار ضغط طلمبة الوقود ورشاشات البنزين',
        description: 'قياس ضغط مسطرة الوقود واختبار نمط الرش والتسريب للرشاشات.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يوصل مانومتر قياس ضغط الوقود', 'يفحص أداء الرشاشات على جهاز تنظيف واختبار الرشاشات', 'يستبدل الفلاتر والأولسيهات التالفة'],
      },
      {
        id: 'lo_aut_201_2',
        code: 'LO 2',
        title: 'فحص إشارات الحساسات (حساس الكرنك، الشكمان، الهواء، الحرارة)',
        description: 'قياس الجهد والمقاومة ورسم الإشارة بجهاز الأوسيلوسكوب.',
        weightHours: 17,
        requiredEvidences: ['performance_checklist', 'knowledge_questioning'],
        performanceCriteria: ['يقيس جهد تغذية الحساسات 5V من الكنترول', 'يفحص إشارة حساس موضع عمود الكرنك CKP', 'يختبر حساس الأكسجين ونسبة خلط الوقود'],
      },
      {
        id: 'lo_aut_201_3',
        code: 'LO 3',
        title: 'استخدام جهاز تشخيص الأعطال السكنر لقراءة أكواد DTC ومسحها',
        description: 'قراءة البيانات الحية Live Data وإجراء اختبارات المشغلات Actuation Tests.',
        weightHours: 17,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يوصل جهاز الفحص بفيشة OBD-II', 'يقرأ ويفسر كود العطل طبقا لكتالوج الصيانة', 'يمسح كود العطل بعد الإصلاح ويتأكد من إطفاء لمبة Check Engine'],
      },
    ],
  },

  // ==========================================
  // قسم تشغيل المعادن والخراطة الميكانيكية (MEC)
  // ==========================================
  {
    id: 'unit_mec_101',
    code: 'MEC-101',
    name: 'تشغيل الأسطح الأسطوانية والمستوية والمخروطية على ماكينات المخرطة',
    category: 'technical_core',
    departmentId: 'dept_mech',
    gradeLevel: 1,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 48,
    description: 'تنفيذ عمليات الخراطة الطولية، الوجهية، الثقب، وقطع القلاووظ طبقا للرسم الهندسي.',
    outcomes: [
      {
        id: 'lo_mec_101_1',
        code: 'LO 1',
        title: 'تثبيت الخامة بالظرف وضبط قلم الخراطة على سنترة الماكينة',
        description: 'سن أقلام الخراطة وضبط زوايا القطع وتثبيت قلم الخراطة ببرج الأقلام.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist'],
        performanceCriteria: ['يثبت الشغلة بظرف المخرطة مع ضبط اللامركزية', 'يسن قلم الخراطة بزوايا القطع المحددة', 'يضبط سن قلم القطع مع ذنبة الغراب المتحرك'],
      },
      {
        id: 'lo_mec_101_2',
        code: 'LO 2',
        title: 'تنفيذ عمليات الخراطة الطولية والتدرج والقطع الوجهي',
        description: 'اختيار سرعة الدوران والتغذية وعمق القطع المناسب لنوع الخامة.',
        weightHours: 16,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يختار سرعة القطع والتغذية طبقا لنوع المعدن', 'ينفذ أقطار متدرجة مطابقة للرسم الهندسي', 'ينفذ تشطيب السطح بجودة خشونة مقبولة'],
      },
      {
        id: 'lo_mec_101_3',
        code: 'LO 3',
        title: 'قياس وتدقيق أبعاد المنتج باستخدام القدمة ذات الورنية والميكرومتر',
        description: 'فحص الأبعاد الداخلية والخارجية والعمق ومطابقتها لحدود التفاوت.',
        weightHours: 16,
        requiredEvidences: ['product_inspection', 'knowledge_questioning'],
        performanceCriteria: ['يقيس الأقطار الخارجية بالميكرومتر بدقة 0.01 مم', 'يقيس الأطوال بالقدمة الورنية بدقة 0.05 مم', 'يسجل بطاقة فحص الجودة ومطابقة العينات'],
      },
    ],
  },

  // ==========================================
  // قسم التبريد وتكييف الهواء (REF)
  // ==========================================
  {
    id: 'unit_ref_101',
    code: 'REF-101',
    name: 'تشكيل ولحام مواسير النحاس وتجميع دوائر التبريد الميكانيكية البسيطة',
    category: 'technical_core',
    departmentId: 'dept_ref',
    gradeLevel: 1,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 40,
    description: 'قص وتوسيع وتفليج مواسير النحاس، ولحام الوصلات بلهب الفضة، واختبار التسريب.',
    outcomes: [
      {
        id: 'lo_ref_101_1',
        code: 'LO 1',
        title: 'قص وثني وتفليج مواسير النحاس بالعدد اليدوية المخصصة',
        description: 'استخدام سكين القطع، ثناية المواسير، وجهاز التفليج وعمل الشفة Flaring.',
        weightHours: 13,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يقص الماسورة بزاوية 90 درجة مع إزالة الرايش', 'يثني الماسورة بنصف القطر دون انخناق', 'ينفذ الفلير والشياك خالي من الشروخ'],
      },
      {
        id: 'lo_ref_101_2',
        code: 'LO 2',
        title: 'لحام وصلات النحاس بلهب الأكسي-أستيلين وسبيكة الفضة والبودرة',
        description: 'ضبط لهب اللحام المحايد وتسخين الوصلة وتغلغل الفضة بالتخاصية الشعرية.',
        weightHours: 14,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يضبط ضغوط الغازات ولهب اللحام المحايد', 'يسخن الوصلة بانتظام حتى درجة الانصهار', 'ينفذ اللحام بتغلغل الفضة الكامل داخل الجلبة'],
      },
      {
        id: 'lo_ref_101_3',
        code: 'LO 3',
        title: 'اختبار تسريب الدائرة بضغط النيتروجين الجاف والماء والصابون',
        description: 'ضغط الوصلات بغاز النيتروجين حتى 150 PSI والتأكد من عدم هبوط الضغط.',
        weightHours: 13,
        requiredEvidences: ['product_inspection', 'knowledge_questioning'],
        performanceCriteria: ['يضغط الدائرة بمنظم النيتروجين الجاف', 'يفحص الوصلات برغوة الصابون', 'يتأكد من ثبات مؤشر الضغط لمدة 15 دقيقة'],
      },
    ],
  },

  // ==========================================
  // قسم الإلكترونيات والحاسبات وتكنولوجيا المعلومات (CMP)
  // ==========================================
  {
    id: 'unit_cmp_101',
    code: 'CMP-101',
    name: 'تجميع واختبار الدوائر الإلكترونية المطبوعة PCB وصيانة الدوائر المنطقية',
    category: 'technical_core',
    departmentId: 'dept_elec',
    gradeLevel: 1,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 42,
    description: 'قراءة المخطط الإلكتروني، لحام المكونات السطحية والعادية، واختبار الدوائر المنطقية الرقمية.',
    outcomes: [
      {
        id: 'lo_cmp_101_1',
        code: 'LO 1',
        title: 'قراءة المخططات الإلكترونية وتحديد قيم المكونات وكود الألوان',
        description: 'حساب قيم المقاومات والمكثفات وتحديد قطبية الدايود والترانزستور والـ ICs.',
        weightHours: 14,
        requiredEvidences: ['knowledge_questioning', 'performance_checklist'],
        performanceCriteria: ['يقرأ كود ألوان المقاومات بدقة', 'يحدد أطراف الترانزستور والدوائر المتكاملة', 'يفحص صلاحية المكونات بجهاز الملتيميتر'],
      },
      {
        id: 'lo_cmp_101_2',
        code: 'LO 2',
        title: 'لحام وفك المكونات الإلكترونية على اللوحات المطبوعة PCB',
        description: 'استخدام كاوية اللحام المضبوطة حرارياً وشفاط القصدير والهوت إير.',
        weightHours: 14,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['ينفذ نقط اللحام لامعة ومخروطية الشكل', 'يتجنب زيادة الحرارة لحماية المسارات', 'ينظف اللوحة بسائل الأيزوبروبيل بعد اللحام'],
      },
      {
        id: 'lo_cmp_101_3',
        code: 'LO 3',
        title: 'فحص واختبار الإشارات الكهربية بجهاز راسم الإشارة (الأوسيلوسكوب)',
        description: 'قياس التردد والجهد وشكل الموجة عند نقاط الاختبار Test Points.',
        weightHours: 14,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يعاير مجس الأوسيلوسكوب 1X/10X', 'يقيس اتساع وزمن الدوري للإشارة', 'يطابق أشكال الموجات مع المخطط المرجعي'],
      },
    ],
  },

  // ==========================================
  // جدارات التوظيف وريادة الأعمال والسلامة لجميع التخصصات (EMP)
  // ==========================================
  {
    id: 'unit_emp_101',
    code: 'EMP-101',
    name: 'مهارات الاتصال الفعال والعمل الجماعي وحل المشكلات في بيئة العمل الفنية',
    category: 'employability',
    departmentId: 'dept_elec',
    gradeLevel: 1,
    term: 'term_1',
    outcomesCount: 3,
    totalHours: 24,
    description: 'إكساب الطالب مهارات التواصل المهني والتعاون الفعال داخل ورش العمل وحل النزاعات وإدارة الوقت.',
    outcomes: [
      {
        id: 'lo_emp_101_1',
        code: 'LO 1',
        title: 'تطبيق مهارات التواصل اللفظي وغير اللفظي الفعال مع الزملاء والرؤساء',
        description: 'الاستماع الإيجابي والتعبير الواضح عن الأفكار الفنية وكتابة التقارير البسيطة.',
        weightHours: 8,
        requiredEvidences: ['performance_checklist', 'knowledge_questioning'],
        performanceCriteria: ['يستخدم لغة مهنية لائقة في الحوار', 'يستمع للتعليمات ويدونها بدقة', 'يقدم تقريراً شفهياً عن سير العمل'],
      },
      {
        id: 'lo_emp_101_2',
        code: 'LO 2',
        title: 'المشاركة الفعالة كعضو فريق عمل لإنجاز مهمة فنية مشتركة',
        description: 'توزيع الأدوار والالتزام بالمسؤوليات ومساعدة الزملاء لتحقيق الهدف الإنتاجي.',
        weightHours: 8,
        requiredEvidences: ['performance_checklist'],
        performanceCriteria: ['يلتزم بالدور المسند إليه في الفريق', 'يتعاون بإيجابية مع أعضاء الفريق', 'يتقبل التغذية الراجعة من قائد الفريق'],
      },
      {
        id: 'lo_emp_101_3',
        code: 'LO 3',
        title: 'تطبيق خطوات حل المشكلات الفنية واتخاذ القرار في الورشة',
        description: 'تحديد المشكلة وتحليل الأسباب واقتراح البدائل وتنفيذ الحل الأنسب.',
        weightHours: 8,
        requiredEvidences: ['performance_checklist', 'knowledge_questioning'],
        performanceCriteria: ['يحدد سبب المشكلة الفنية بدقة', 'يقترح حلولاً مبتكرة وقابلة للتطبيق', 'يقيم نتيجة القرار المتخذ'],
      },
    ],
  },
  {
    id: 'unit_emp_201',
    code: 'EMP-201',
    name: 'ريادة الأعمال وإعداد دراسات الجدوى وتأسيس المشروعات الفنية الصغيرة',
    category: 'employability',
    departmentId: 'dept_elec',
    gradeLevel: 2,
    term: 'term_2',
    outcomesCount: 3,
    totalHours: 30,
    description: 'توليد أفكار المشروعات الصناعية، إعداد خطة العمل، حساب التكاليف والأرباح، والتسويق الإلكتروني.',
    outcomes: [
      {
        id: 'lo_emp_201_1',
        code: 'LO 1',
        title: 'توليد وتقييم فكرة مشروع فني إنتاجي يلبي احتياجات السوق المحلي',
        description: 'دراسة السوق وتحليل نقاط القوة والضعف والفرص والتهديدات SWOT.',
        weightHours: 10,
        requiredEvidences: ['product_inspection', 'knowledge_questioning'],
        performanceCriteria: ['يحدد فكرة مشروع قابلة للتنفيذ في التخصص', 'يحدد الفئات المستهدفة والمنافسين', 'يصيغ الميزة التنافسية للمشروع'],
      },
      {
        id: 'lo_emp_201_2',
        code: 'LO 2',
        title: 'إعداد دراسة الجدوى الفنية والمالية وحساب نقطة التعادل والتسعير',
        description: 'حساب تكاليف الخامات والعمالة والمعدات وتحديد سعر البيع وهامش الربح.',
        weightHours: 10,
        requiredEvidences: ['product_inspection'],
        performanceCriteria: ['يحسب التكاليف الثابتة والمتغيرة بدقة', 'يحدد سعر بيع تنافسي للمنتج أو الخدمة', 'يحسب العائد المتوقع وفترة الاسترداد'],
      },
      {
        id: 'lo_emp_201_3',
        code: 'LO 3',
        title: 'إعداد خطة التسويق وعرض فكرة المشروع (Pitching) أمام المستثمرين',
        description: 'تصميم هوية المنتج واستخدام وسائل التواصل الاجتماعي في الترويج والعرض المقنع.',
        weightHours: 10,
        requiredEvidences: ['performance_checklist', 'product_inspection'],
        performanceCriteria: ['يعد نموذج خطة عمل مصغر Canvas', 'يصمم مادة تسويقية جذابة للمنتج', 'يقدم عرضاً مقنعاً لفكرة المشروع في 3 دقائق'],
      },
    ],
  },
];

export const MOCK_COMPETENCY_ASSESSMENTS: StudentCompetencyAssessment[] = [];

export const MOCK_SOCIAL_CASES: import('@/types').SocialCaseRecord[] = [];

export const MOCK_COMPETENCY_VERIFICATIONS: import('@/types').CompetencyVerificationRecord[] = [];

export const MOCK_STUDENT_PORTFOLIOS: import('@/types').StudentPortfolioRecord[] = [];

